#!/usr/bin/env node
/**
 * Writes frontend/static/js/config.js from API_BASE / VITE_API_BASE.
 * Used by Vercel build so the static UI can call the Render backend.
 */
const fs = require("fs");
const path = require("path");

const apiBase = (process.env.API_BASE || process.env.VITE_API_BASE || "").replace(/\/$/, "");
const outPath = path.join(__dirname, "static", "js", "config.js");
const contents = `// Generated by build-config.js - do not edit on Vercel deploys.
window.APP_CONFIG = {
  API_BASE: ${JSON.stringify(apiBase)},
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, contents, "utf8");
console.log(`Wrote ${outPath} with API_BASE=${apiBase || "(same-origin)"}`);
